### ISSUE TITLE
Deprecation error points to "Ocamlcommon" instead of "Ocaml_common"

### ISSUE THREAD

**Issue by ryco117** [ocaml-ppx/ppxlib#101]
Hi, I'm trying to write my first ppx rewriter for Ocaml using ppxlib and when I tried to open Ast_mapper I was confronted with the error `Accessing this module directly is deprecated, use Ocamlcommon.Ast_mapper instead`, however it took me quite some searching to find that the module is actually called "Ocaml_common". This should be fixed.

(As an aside, a link to the most up-to-date documentation would be greatly appreciated as most of the PPX docs and tutorials are very old and inconsistent :/ )

**Comment by pitag-ha** [comment]
I see that that's confusing. That error is raised by `Ocaml_shadow` from `ocaml-compiler-libs`. So I think we can't do anything about the wording from the ppxlib side. If you do see something, please feel free to reopen the issue.
