### ISSUE TITLE
can we use ocamlformat in ppxlib?

### ISSUE THREAD

**Issue by dwang20151005** [ocaml-ppx/ppxlib#120]
Ocamlformat is the default in Jane Street, but I don't know how people outside Jane Street feel about it.

Would the ppxlib maintainers entertain a pull request that ocamlformat'ed ppxlib?

**Comment by diml** [comment]
It depends on projects, some adopt it some don't. Adopting ocamlformat for ppxlib seems good to me. FTR, we plan to adopt it for `ocaml-ppx/ppx`.

**Comment by dwang20151005** [comment]
Carl pointed out that what I want is apply-style, i.e., ocamlformat with the Jane Street profile plus some other details. Enabling ocamlformat in dune in the github repo doesn't get me automatic formatting in my emacs within Jane Street.

I still think it's a good idea to enable ocamlformat for ppxlib in dune, but it doesn't solve my problem, so I guess I'm not going to work on it.

**Comment by diml** [comment]
Enabling ocamlformat in emacs is quite easy:

```scheme
(require 'ocamlformat nil t)
(defun my-tuareg-mode-hook ()
  (add-hook 'before-save-hook 'ocamlformat-before-save))
(add-hook 'tuareg-mode-hook 'my-tuareg-mode-hook)
```

The difficult part when we work on our JS uid boxes is to "undo" the Jane Street setup when working on github repositories. I have some elisp code for this if you are interested.

**Comment by dwang20151005** [comment]
Yes, can you email me the code?  We might make this part of the standard
setup.

**Comment by diml** [comment]
Sure!
