### ISSUE TITLE
Port bitstring to ppxlib

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml-ppx/ppxlib#132]
https://bitbucket.org/thanatonauts/bitstring/src/master/

**Comment by pveber** [comment]
I have proposed a patch for `bitstring`, see the [pull request](https://bitbucket.org/thanatonauts/bitstring/pull-requests/3/switch-to-ppxlib/diff).

One thing I'm not absolutely sure of is my `open Ast_builder.Default` at the top of the module. Is it alright?

**Comment by NathanReb** [comment]
From a quick look it looks good! Opening `Ast_builder.Default` is indeed alright!

**Comment by kit-ty-kate** [comment]
It seems that this issue can be closed as bitstring was migrated to ppxlib in https://github.com/xguerin/bitstring/pull/22 (part of bitstring 4.0.0)

**Comment by pitag-ha** [comment]
Thanks @kit-ty-kate for pointing that out, and of course, thanks @pveber for the port!
