### ISSUE TITLE
Port metapp to ppxlib

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml-ppx/ppxlib#136]
https://github.com/thierry-martinez/metapp

**Comment by jeremiedimino** [comment]
@thierry-martinez, since you recently ported ppx_deriving to ppxlib, I'm thinking that you might already be quite familiar with ppxlib and the work of porting a project from ocaml-migrate-parsetree to ppxlib.

Are you happy to port metapp to ppxlib, or do you prefer that we take care of it?

FTR, this is in the context of ocaml-migrate-parsetree 2.0.0: https://discuss.ocaml.org/t/ocaml-migrate-parsetree-2-0-0/5991/6

**Comment by thierry-martinez** [comment]
@jeremiedimino , thank you for pinging me on this issue. I will take care of it as soon as possible!

**Comment by jeremiedimino** [comment]
No problem, and thanks for taking care of it!

**Comment by pitag-ha** [comment]
I'm closing this, since `metapp` has been [ported](https://github.com/thierry-martinez/metapp/commit/0ad85ceca2945451c513b22de0dc6ae94f651bff) a while ago. Thanks @thierry-martinez!
