### ISSUE TITLE
Port ocaml-monadic to ppxlib

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml-ppx/ppxlib#138]
https://github.com/zepalmer/ocaml-monadic

**Comment by tatchi** [comment]
I started working on this one :)

**Comment by pitag-ha** [comment]
I'm closing this, since the port has been merged already. Thanks @tatchi!

By the way, @zepalmer would you mind releasing `ocaml-monadic` now that it's ported to ppxlib? Having a released versio would be great!
