### ISSUE TITLE
Port ppx_gen_rec to ppxlib

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml-ppx/ppxlib#142]
https://github.com/flowtype/ocaml-ppx_gen_rec

**Comment by giltho** [comment]
Waiting for https://github.com/flowtype/ocaml-ppx_gen_rec/pull/5 to be merged, and that issue is good to go :)

**Comment by giltho** [comment]
It's merged ! This can be closed :)

**Comment by pitag-ha** [comment]
Thanks @giltho!
