### ISSUE TITLE
Port ppx_import to ppxlib

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml-ppx/ppxlib#143]
https://github.com/ocaml-ppx/ppx_import

ppx_import also relies on the typedtree. This part of the code should be left as-it.

**Comment by tatchi** [comment]
Started working on this one. I'll try to open a PR soon :)

**Comment by pitag-ha** [comment]
@tatchi's [PR](https://github.com/ocaml-ppx/ppx_import/pull/54) for that has now been merged. Thanks a lot for your great work, @tatchi!
