### ISSUE TITLE
Port zarith-ppx to ppxlib

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml-ppx/ppxlib#145]
https://github.com/Drup/Zarith-ppx

**Comment by hhugo** [comment]
Why does this point to sedlex ?

**Comment by jeremiedimino** [comment]
It was a typo, I fixed it

**Comment by jeremiedimino** [comment]
We were discussing on slack whether we should look into porting Zarith-ppx to ppxlib ourselves, or release the Jane Street ppx rewriter that does the same as Zarith-ppx. Since Zarith-ppx has no users in opam, we simply decided to drop porting Zarith-ppx to ppxlib from our stack. We'll do the same for other ppx rewriters that have no users in opam.
