### ISSUE TITLE
Access `Code_path` in custom attribute rewriter

### ISSUE THREAD

**Issue by alexfedoseev** [ocaml-ppx/ppxlib#174]
I have a logging ppx which has a number of extension points and one attribute. In extension rules, I can access `Code_path` data, but apparently, I can't access it in the attribute rewriter which is passed via `impl` arg to `Driver.register_transformation` as extended `Ast_traverse.map` object.

**Comment by NathanReb** [comment]
You can use `Ast_traverse.map_with_expansion_context` instead in your `impl` function. #173 which was just merged adds accessors for the `Expansion_context.Base.t` type and that should do the trick for you.

I'll try to cut a release this week!

**Comment by NathanReb** [comment]
I'm closing this but feel free to re-open it if the proposed solution doesn't work for you!

**Comment by alexfedoseev** [comment]
Oh, perfect timing lol. Thank you!

**Comment by alexfedoseev** [comment]
@NathanReb I have a question on how to use `Ast_traverse.map_with_expansion_context` in general. AFAIU to be able to pass it to `impl` during registration, I need to construct base context which requires `file_path`. In `File_path`, this value is taken from `Location.t` which I don't have at the moment of registration. So all the code paths can't be correctly constructed without the base file path. Can you suggest how to handle it?

**Comment by NathanReb** [comment]
You can extract it from the first location you find in the `structure` argument:
```ocaml
let impl structure =
  let file_path =
    match structure with
    | [] -> "" (* It is likely not to matter here because you'd have nothing to transform anyway *)
    | {pstr_loc; _} :: _ -> pstr_loc.loc_start.pos_fname
  in
  ...
```

There is code for this in the driver if you want to take a look: https://github.com/ocaml-ppx/ppxlib/blob/master/src/driver.ml#L195.
We should probably provide an Expansion_context there as well so that this along with the tool_name are properly filled but that's breaking change so we'd have to do this carefully.

**Comment by alexfedoseev** [comment]
Right, yeah. I was confused that during registration I don't have any structure (so I can use `File_path.get_default_path_str`) but structure is provided as a first argument to `impl` so I can use that. Thank you!
