### ISSUE TITLE
Location.Error is not the same exception as compiler-libs' Location.Error

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-ppx/ppxlib#195]
Some issue arose when `ppx_blob` was ported to `ppxlib`.
The old ppxlib-free code raised `Ocaml_common.Location.Error ...` and the first proposal tried to use `Ppxlib.Location.Error ...` instead. However this exception is meant to be caught in the compiler and since `Ppxlib.Location.Error` is a totally new exception, it was left uncaught and did not display the correct pretty error message.

See: https://github.com/jberdine/ppx_blob/pull/1 & https://github.com/johnwhitington/ppx_blob/pull/20#issuecomment-691940479

**Comment by pitag-ha** [comment]
Yes, that was indeed a bug in ppxlib. Thanks for raising it! It was fixed in #242.
