### ISSUE TITLE
Expose Utils.Ast_io.

### ISSUE THREAD

**Issue by arozovyk** [ocaml-ppx/ppxlib#268]
Hi, i'm currently working on AST exploration features for VSCode extension: [vscode-ocaml-platform](https://github.com/arozovyk/vscode-ocaml-platform/tree/react-ast-explorer), and i would like to use the `Utils.Ast_io.read` function in order to get the tranformed AST value from `.pp.ml.`  (which i do locally this way: [link](https://github.com/arozovyk/vscode-ocaml-platform/blob/0b5112442ae12cb843d12ad579352e9282a4a579/src/ppx_utils.ml#L26)). 

Would it be possible to expose this module ?

**Comment by pitag-ha** [comment]
Hi @arozovyk, the AST exploration feature for VSCode is super cool, thanks for working on that!

For me it's ok to expose `Utils.Ast_io`. But that module is currently a bit `ppxlib`-internals specific. I'm wondering if we should expose that whole module as is or if it would be enough to expose certain parts that are less specific. From what I understand, you have a binary and need to
1. consume the magic number as in [`read_magic`](https://github.com/ocaml-ppx/ppxlib/blob/master/src/utils.ml#L114-L121). But you already know, unless something is wrong, it will be the impl magic number from the current compiler.
2. consume the `input name` as done [here](https://github.com/ocaml-ppx/ppxlib/blob/master/src/utils.ml#L145). You also don't seem to need the `input name`, at least not currently, but you need to consume what's in the channel before the AST.
3. read the AST and convert it to the `ppxlib`-AST as done [here](https://github.com/ocaml-ppx/ppxlib/blob/master/src/utils.ml#L146-L148)

Is that what you need?

**Comment by arozovyk** [comment]
Hi, @pitag-ha, thanks for replying!  

Your comment made me remember that I wanted to add support for `Inft` and not only `Impl` as I showed [here](https://github.com/arozovyk/vscode-ocaml-platform/blob/0b5112442ae12cb843d12ad579352e9282a4a579/src/ppx_utils.ml#L26).

So basically i will need the whole `ast` field as you can see [here](https://github.com/arozovyk/vscode-ocaml-platform/blob/ppx_tools/src/ppx_utils.ml#L41-L46).  

And i feel like everything that i need (modulo stuff that you mentionned i.e. `input_name`)  is done by [from_channel](https://github.com/ocaml-ppx/ppxlib/blob/master/src/utils.ml#L123-L166)  
So exposing something like : 

```OCaml
 let read_bin fn = 
        In_channel.with_file fn ~f:(from_channel ~input_kind:Necessarily_binary ) 
```
Plus `Intf_or_impl` module should do the job. 

If that's not an option for some reason, maybe simplify the `from_channel` function, something along the lines of:

```OCaml
match read_magic ch with Error s ->  Error (*?*)
        | Ok s -> (
            match Find_version.from_magic s with
            | Intf (module Input_version : OCaml_version) ->
                let _ : string = input_value ch in
                let ast = input_value ch in
                let module Input_to_ppxlib = Convert (Input_version) (Js) in
                Intf_or_impl.Intf (Input_to_ppxlib.copy_signature ast) 
            | Impl (module Input_version : OCaml_version) ->
                let _ : string = input_value ch in
                let ast = input_value ch in
                let module Input_to_ppxlib = Convert (Input_version) (Js) in
                Intf_or_impl.Impl (Input_to_ppxlib.copy_structure ast)
            | Unknown -> Error (*?*)
```
 can be done? 

Please tell me what do you think.

**Comment by pitag-ha** [comment]
> So exposing something like :
>```
> let read_bin fn = 
>       In_channel.with_file fn ~f:(from_channel ~input_kind:Necessarily_binary ) 
>```
Yes, that sounds like a good idea to me.

>Plus Intf_or_impl module should do the job.

 Do you mean the whole `Intf_and_impl` module or `Intf_and_impl.t`?

**Comment by pitag-ha** [comment]
Do you want to implement that and open a PR?

**Comment by smorimoto** [comment]
I think we can close this now.

**Comment by pitag-ha** [comment]
> I think we can close this now.

Indeed. Thanks!
