### ISSUE TITLE
Question: how to add attributes (in)to extension point

### ISSUE THREAD

**Issue by Kakadu** [ocaml-ppx/ppxlib#272]
I want to generate a few type definitions using extension point and these definitions should have user-defined deriving attributes.  But ppxlib doesn't allow me (Error: Attributes not allowed here) to set neither using the 1st variant nor the 2nd. Why it does that and how should I achieve what I want?

```ocaml
[%%distrib
  type nonrec t = A [@@deriving gt1]
  type ground = t
] [@@deriving gt2]
```

**Comment by pitag-ha** [comment]
> I want to generate a few type definitions using extension point and these definitions should have user-defined deriving attributes.

If I understand your situation correctly, you could add the attribute to your type definition inside the payload of the extension node. The extension node [will be applied first](https://github.com/pitag-ha/ppxlib/blob/test-derivers-extension-nodes-order/test/driver/order_derivers_extension_notes/run.t#L31-L39). When expanding the extension node, you need to add the attribute received in the payload to the type definition it generates. The attribute will then be applied to the generated type definition.

> Why it does that

The OCaml AST doesn't expect attributes attached to [structure items](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L752-L788). It does expect e.g. [attributes attached to type declarations](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L443) though.

**Comment by Kakadu** [comment]
I made some progress. It looks like function `Ast_pattern.type_declaration_attributes` wil solve my issue

**Comment by NathanReb** [comment]
Could you give us a bit more context about your ppx? What does it expect as a payload, what does it generate, etc... We might be able to provide more help with that kind of information !

**Comment by Kakadu** [comment]
It looks like I managed to do what I want. In reality I didn't know a right way to first-class match attributes, so all input code with attributes was declined. And I thought that it is an administrative limitation of ppxlib, but in fact my patterns were not precise enough
