### ISSUE TITLE
Driver and pretty printing output

### ISSUE THREAD

**Issue by Kakadu** [ocaml-ppx/ppxlib#273]
I'm using `Ppxlib.Driver.standalone ()` to create executable for my rewriter to better debug them. It looks like by default formatter has a small margin (about 80 characters) and it would be great to make it configurable. It should be done near https://github.com/ocaml-ppx/ppxlib/blob/master/src/driver.ml#L952

Could you recommned right way to it? An extra command like switch? Will a PR like that be merged?

**Comment by pitag-ha** [comment]
Maybe to format the output in a certain way, you could pipe it into ocamlformat? Something along the lines
```
your_driver.exe your_file.ml | ocamlformat - --impl --margin=90
```

**Comment by Kakadu** [comment]
It's a decent advice, thanks!
