### ISSUE TITLE
Restore ocamlbuild plugin?

### ISSUE THREAD

**Issue by drvink** [ocaml-ppx/ppxlib#29]
I've been having to maintain a pin of ppxlib that restores the `ocamlbuild` plugin, for compatibility with BinaryAnalysisPlatform/bap#820. Since the changes consist literally of nothing but reverting the deletion of files in the `ocamlbuild_plugin/` directory, I would like to request that this support be restored. I can make a PR easily.

Otherwise, we will need to vendor a separate version of ppxlib somewhere, which will be a lot of trouble since we will need to change the name etc. to not conflict with other installations of ppxlib (unless there is some easy way of simply splitting the plugin into a separate, optional package).

**Comment by diml** [comment]
Why not simply distribute the plugin as a separate package?

**Comment by drvink** [comment]
I wasn't sure whether that would work correctly, but it looks pretty standalone, so I think that might work. Let me give it a shot.

**Comment by drvink** [comment]
Ah, this was where I figured there might be a problem:

```
arch-vm[1171]:~/prog/src/ocaml/ppxlib-ocamlbuild% make
jbuilder build --dev --auto-promote @cinaps @install
File "ocamlbuild_plugin/jbuild", line 3, characters 2-33:
Error: The current scope doesn't define package "ppxlib".
The only packages for which you can declare elements to be installed in this directory are:
- ppxlib-ocamlbuild (because of ppxlib-ocamlbuild.opam)
make: *** [Makefile:5: default] Error 1
```

Is there a workaround? It's not a big deal if we have to change our ocamlbuild file to use `Blah_ppxlib_ocamlbuild` instead of `Ppxlib_ocamlbuild`, though.

**Comment by drvink** [comment]
I've done the latter. Sorry for the noise!
