### ISSUE TITLE
Two questions about first class patterns: dropping and giving a name to subvalues

### ISSUE THREAD

**Issue by Kakadu** [ocaml-ppx/ppxlib#310]
While using `Ast_pattern` I got a few issues. 

1) I can't find any function that ignores part of AST (i.e. wildcard semantics). Right now `__` behaves as pattern variable and obliges to receive that value in "action code" (I'm using parser-generator vocabulary here). 
2) I can't find any way to give another name to part of AST, i.e. I want something similar to `as` keyword in OCaml. If it would be available we could express matching a structure item which is a type declaration in more convenient manner, something like 
```
pstr_type nonrecursive  
  (__as (type_declaration ~name:drop ~params:drop ~cstrs:drop ~kind:drop  ~private_:drop ~manifest:drop))
- : (Ppxlib__.Import.structure_item,
     Ppxlib__.Import.structure_item -> '_weak1, '_weak1)
    Ppxlib__.Ast_pattern0.t
= Ppxlib__.Ast_pattern0.T <fun>
(* future hypothetical type *)
```

If I'm not  blind indeed, I probably could make a PRs this functionality.

**Comment by pitag-ha** [comment]
Hey @Kakadu , thanks for the issue and sorry for the delay in answering. Extending `Ast_pattern` sounds great! I have a couple of questions about your example just for better understanding:

What do you mean with `drop`? Is that the name you give to the "function that ignores parts of the AST" as you describe in 1.?

And, what exactly is it that you want to achieve in your example? What I understand is that you'd like to

> express matching a structure item which is a type declaration

Is that correct? If so, is that similar to the following?
```
pstr (pstr_type nonrecursive (__ ^:: nil) ^:: nil)
```

**Comment by Kakadu** [comment]
@pitag-ha We together are masters of delayed answers!

There is a chance that my example from the issue is not the best and you can indeed express what I wanted. But what about "single type declaration with any recursivity flag"?

Also I made a PR where I motivated my desire to have new combinators in context of writing a linter. Could you look into it?

**Comment by pitag-ha** [comment]
Oh, I somehow missed that PR, thanks for pinging me! I'll review tomorrow.

Btw, I've just seen that there's another issue about `drop` with a very similar motivation as what your saying about "single type declaration with any recursivity flag": #89

**Comment by Kakadu** [comment]
Resolved in https://github.com/ocaml-ppx/ppxlib/pull/313
