### ISSUE TITLE
`Ast_pattern.many` buggy?

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ppxlib#331]
The combinator `Ast_pattern.many` has the following signature:

https://github.com/ocaml-ppx/ppxlib/blob/770080baac7184326203974599d48cc2035b525e/src/ast_pattern.mli#L160

which seems a bit fishy. Shouldn't the signature be something like

```ocaml
val many : ('a, 'c -> 'd, 'd) t -> ('a list, 'c list -> 'd, 'd) t 
```

instead?

Looking at the implementation:

https://github.com/ocaml-ppx/ppxlib/blob/770080baac7184326203974599d48cc2035b525e/src/ast_pattern.ml#L175-L176

the use of the identity `(fun x -> x)` looks out of place. Shouldn't it be something like

```ocaml
let many (T f) =
  T (fun ctx loc l k ->
    let rec aux accu = function
      | [] -> k (List.rev accu)
      | x :: xs ->
        f ctx loc x (fun x -> aux (x :: accu) xs)
    in
    aux [] l)
```

instead?

**Comment by panglesd** [comment]
I agree. The current signature is only constraining the use of `many`.

Nice continuation-passing style implementation! Do you want to open a PR?

**Comment by nojb** [comment]
> Nice continuation-passing style implementation! Thanks! Do you want to open a PR?

Sure, see #333
