### ISSUE TITLE
Empty `ptyp_variant` and `pexp_match` do not produce errors and syntactically incorrect code

### ISSUE THREAD

**Issue by maurobringolf** [ocaml-ppx/ppxlib#353]
I am working on a ppx deriver and just encountered a relatively surprising scenario. I am generating a closed variant type `t` using `ptype_variant` and a pattern match over expressions of this type using `pexp_match`. Now I discovered that for some inputs my list of constructors/cases is empty. This is a mistake on my part and clearly not a bug in ppxlib. But I was surprised as to *when* and *how* things failed:

There were no compile (ppxlib runtime) errors and `Ppxlib.Driver.standalone ()` happily produced the following:

```ocaml
(* What is supposed to be my variant type *)
type t = []

(* Match expression with empty list of cases over expression of type t *)
(match e with)
```

The code also runs fine although the text version above is syntactically incorrect (the `match` term) and different from the AST (the type `t` is not a variant type). But of course the code only runs because there are no values in type `t` with which the empty match can be evaluated. I forced it by passing `Obj.magic` into the function evaluating this expression and got:

```
Fatal error: exception "Match_failure _none_:1:-1"
```

---

I am not sure what the desired behavior in this case actually is, but from my point of view it would have been more helpful if ppxlib rejected my empty lists and my code didn't compile.

**Comment by panglesd** [comment]
If I understand correctly, you produced an AST that is impossible to obtain by parsing an ocaml syntax. So, when trying to print it as ocaml syntax, it produces a syntax errors (`(match e with)` makes sense to me, but `type t = []` for an empty closed type is strange).

Could you confirm by dumping the parsetree for your above example?

About the issue itself, you might be right that `ppxlib` could display an error, or a warning, when the parsetree does not have a corresponding syntax. It should not be hard in the specific case of empty of pattern-matching or empty closed type, but more difficult in general (we could pretty-print the result, parse it again and check that the two parsetrees are the same?).

However, that would be a breaking change that can introduce subtle bugs...

Thanks for your report!

**Comment by maurobringolf** [comment]
Thanks for the quick reply!

> Could you confirm by dumping the parsetree for your above example?

The `type t = []` part is:

```txt
(Pstr_type Recursive
 (((ptype_name
	((txt order_attribute)
	 (loc
	  ((loc_start
		((pos_fname examples/3-relation/model.ml)
		 (pos_lnum 1) (pos_bol 0) (pos_cnum 0)))
	   (loc_end
		((pos_fname examples/3-relation/model.ml)
		 (pos_lnum 1) (pos_bol 0) (pos_cnum 49)))
	   (loc_ghost false)))))
   (ptype_params ()) (ptype_cstrs ())
   (ptype_kind Ptype_abstract) (ptype_private Public)
   (ptype_manifest
	(((ptyp_desc (Ptyp_variant () Closed ()))
	  (ptyp_loc
	   ((loc_start
		 ((pos_fname examples/3-relation/model.ml)
		  (pos_lnum 1) (pos_bol 0) (pos_cnum 0)))
		(loc_end
		 ((pos_fname examples/3-relation/model.ml)
		  (pos_lnum 1) (pos_bol 0) (pos_cnum 49)))
		(loc_ghost false)))
	  (ptyp_loc_stack ()) (ptyp_attributes ()))))
(ptype_attributes ())
	(ptype_loc
	 ((loc_start
	   ((pos_fname examples/3-relation/model.ml)
		(pos_lnum 1) (pos_bol 0) (pos_cnum 0)))
	  (loc_end
	   ((pos_fname examples/3-relation/model.ml)
		(pos_lnum 1) (pos_bol 0) (pos_cnum 49)))
	  (loc_ghost false))))))
```

and the empty match term should be:

```
(Pexp_match
 ((pexp_desc
   (Pexp_ident
	((txt
	  (Lident
	   attr))
	 (loc
	  ((loc_start
		((pos_fname examples/3-relation/model.ml) (pos_lnum 1) (pos_bol 0) (pos_cnum 0)))
	   (loc_end
		((pos_fname examples/3-relation/model.ml) (pos_lnum 1) (pos_bol 0) (pos_cnum 49)))
	   (loc_ghost false))))))
		(pexp_loc
		 ((loc_start ((pos_fname examples/3-relation/model.ml) (pos_lnum 1) (pos_bol 0) (pos_cnum 0)))
		  (loc_end
		   ((pos_fname examples/3-relation/model.ml) (pos_lnum 1) (pos_bol 0) (pos_cnum 49))) (loc_ghost false)))
		(pexp_loc_stack
		 ())
(pexp_attributes
 ())) ())
```

---

> (we could pretty-print the result, parse it again and check that the two parsetrees are the same?).

This is a property I expected in absense of errors. But I can imagine that there are edge cases where it does not hold. I would be interested in seeing/doing this kind of test though.

**Comment by panglesd** [comment]
Your issue raised the question: Currently, ppxlib allows to generate parsetrees that do not correspond to a source code (no source code would be parsed to it). Should we prevent this, for instance by checking that pretty-printing -> parsing is the identity?

After discussing a bit about it, I don't think we are going to do include such a feature/test.

It seems that the compiler will already reject as "invalid" some AST, by checking the invariants as defined in [this file](https://github.com/ocaml/ocaml/blob/trunk/parsing/ast_invariants.ml). So this is already a safe-guard against too bad ASTs.
I don't see a reason to reject more AST than the compiler.

In your specific case, I was very surprised that there were no "this pattern-matching is not exhaustive." error. However, I could reproduce the behavior. So it seems the compiler does not checks this after being given the rewritten AST.
I don't know why it is the case. Maybe it make sense to open an issue on the ocaml repo?

**Comment by maurobringolf** [comment]
> After discussing a bit about it, I don't think we are going to do include such a feature/test.

Okay, I think that is a sensible design decision.

> So it seems the compiler does complain for non-exhaustive pattern-match except when the case list is empty...

Me too, but I guess in some sense it is correct. Since the pattern-match is over an expression of the empty variant type I generated, there is no case to match because there are no constructors in it. That's why I am not really expecting an exhaustiveness error, but rather an error about the empty variant type itself.

> Maybe it make sense to open an issue on the ocaml repo?

I will, it seems like ppxlib plays no part in the confusing behavior. But it is the only way I know how to create an OCaml AST and run it through the compiler directly. Maybe you can give me a hint on how to reproduce the behavior without using ppxlib?

**Comment by panglesd** [comment]
> Me too, but I guess in some sense it is correct. Since the pattern-match is over an expression of the empty variant type I generated, there is no case to match because there are no constructors in it. That's why I am not really expecting an exhaustiveness error, but rather an error about the empty variant type itself.

It's true that in your specific case (empty matching on empty variant) an exhaustiveness error might not make sense, but I tried, and there is also no exhaustiveness error on an empty pattern-match on a string, which makes less sense...

> I will, it seems like ppxlib plays no part in the confusing behavior. But it is the only way I know how to create an OCaml AST and run it through the compiler directly. Maybe you can give me a hint on how to reproduce the behavior without using ppxlib?

When you run the ocaml compiler on the command line, you can add `-ppx <exe_name>` so that the compiler, after getting the parsetree, call `<exe_name>` and pass it the AST (`<exe_name>` reads the marshalled parsetree from a file and unmarshalls it). When the program has finished rewriting, it gives a parsetree back to the compiler by using the same marshalling-unmarshalling method.
Ppxlib generate a driver: an executable to pass to the `-ppx` flag. But the compiler does not know if the driver has been generated by ppxlib or not.
So I don't think it is needed to reproduce the problem without ppxlib to open an issue on ocaml itself.

However, I don't think it makes sense to open an issue about no warning on empty variant (it just means that empty variants are allowed). I do think it makes sense to open an issue on "no warning on empty match case list", but this is somehow unrelated to your initial problem, so I can open the issue myself!
