### ISSUE TITLE
Documentation Doesn't Explain How to Generate a Type Definition that has a PPX Annotation 

### ISSUE THREAD

**Issue by llee454** [ocaml-ppx/ppxlib#359]
The documentation does not explain how to create a type definition that has a PPX annotation. I would like to generate code like the following:

```
type t = unit [@@deriving example]
```

The library defines a type to represent type declarations: `type_declaration`. This type has a field named `attribute` that should represent the `[@@deriving example]` part. There is a function named `attribute` that creates these attributes. The problem is that this function expects a `payload` value. In the example given, the payload should be an expression, namely: `example`; but, the `attribute` function only accepts structures and signatures.

Is it possible to create a PPX deriver that generates statements like the one given above? If so, is this documented in the manual? If not, can it be added?

Thanks,

**Comment by panglesd** [comment]
A good way to know how to create a specific AST entry is to use the `-dparsetree` option of `ocaml` or `utop`, which "dumps" the AST to the standard output whenever you send structure items to the tool.

So, if you write `type t = unit [@@deriving example];;` on `utop` or `ocaml` started with `-dparsetree`, you get the following answer:

```ocaml
Ptop_def
  [
    structure_item (//toplevel//[1,0+0]..[1,0+34])
      Pstr_type Rec
      [
        type_declaration "t" (//toplevel//[1,0+5]..[1,0+6]) (//toplevel//[1,0+0]..[1,0+34])
          attribute "deriving"
            [
              structure_item (//toplevel//[1,0+26]..[1,0+33])
                Pstr_eval
                expression (//toplevel//[1,0+26]..[1,0+33])
                  Pexp_ident "example" (//toplevel//[1,0+26]..[1,0+33])
            ]
          ptype_params =
            []
          ptype_cstrs =
            []
          ptype_kind =
            Ptype_abstract
          ptype_private = Public
          ptype_manifest =
            Some
              core_type (//toplevel//[1,0+9]..[1,0+13])
                Ptyp_constr "unit" (//toplevel//[1,0+9]..[1,0+13])
                []
      ]
  ]

type t = unit
```

This corresponds to the parsetree of the expression. You can see that `example` is indeed a structure consisting of a single structure item, consisting of the evaluation of an expression. *So, contrary to the appearance, it is not an expression!*.

So, you just need to use `Ast_builder.pstr_eval` to turn an expression into a structure item and wrap the result in a list. I think it solves your particular issue. About the documentation, it will be partly rewritten soon, and I will try to include "tricks" such as using `-dparsetree` to understand better the AST.

**Comment by llee454** [comment]
Thanks @panglesd
