### ISSUE TITLE
0.28 release

### ISSUE THREAD

**Issue by staronj** [ocaml-ppx/ppxlib#378]
Would it be possible to make a release of ppxlib? We are using a newer revision than 0.27 internally, and it's blocking us from releasing some of our internal packages externally.

**Comment by kit-ty-kate** [comment]
I'm not sure why I'm being pinged here as I'm not a maintainer of ppxlib

**Comment by staronj** [comment]
Sorry for omitting the context - I just wanted to keep you in a loop, as you were pinging us on releasing new versions of Jane Street packages. 

@tov recently released new version of base, but as updating of more packages is required, manual patching stops being a viable approach. I'm working on unblocking the release of internal packages, so that manual patching is not necessary.

**Comment by staronj** [comment]
0.28 version of ppxlib was released

**Comment by pitag-ha** [comment]
Yes, it's released and the opam-repo release PR is merged now.

Btw, there are also two Jane Street PPXs that aren't compatible with this `ppxlib` version, at least not on their public branch. I opened patch PRs some time ago when releasing the `ppxlib` version that broke them:
- https://github.com/janestreet/ppx_jsonaf_conv/pull/1
- https://github.com/janestreet/ppx_yojson_conv/pull/13

Unless you already have similar patches on your internal Jane Street branches, you might have to merge them to be able to do a bulk release.
