### ISSUE TITLE
Follow current OCaml trunk (on a separate branch?)

### ISSUE THREAD

**Issue by shym** [ocaml-ppx/ppxlib#387]
This is a feature request.
As `ppxlib` has so many reverse dependencies, it is often the point of failure when testing the current OCaml trunk: we often see people reaching out for help when `opam` fails to find how to install some package in their `trunk` switch, with no clue that the incompatibility is basically `ppxlib` - OCaml trunk.
I suppose that’s why #383 was opened; at least that’s why I had also created a [`5.1`](https://github.com/shym/ppxlib/tree/5.1) branch in my fork, to test the current trunk compiler with our [ocaml-multicore/multicoretests](https://github.com/ocaml-multicore/multicoretests). So I guess sharing that work would be useful to quite a few people.

I finally managed to update my branch to support the AST change from last week but I had to write by hand (boring so easy) code that is normally generated (I guess) because I didn’t manage to get the instructions at the top of `ast/ast.ml` working. My branch could of course be turned into a PR.

**Comment by panglesd** [comment]
I think that's a very good idea.

However, it cannot be on the `main` branch (for instance, that would tie the ppxlib releases with the ocaml ones).
We could have an `ocaml-trunk` branch, based on the last `ppxlib` release (to avoid other breaking changes to be in the branch), and keep it updated with regards to ocaml's `trunk`.
To use ppxlib in a `trunk` switch, the only thing to do would be to pin `ppxlib` to this branch.

**Comment by pitag-ha** [comment]
I also think that having a branch with `trunk` support is an ok temporary solution. @ElectreAAS (from the `current-bench` team) and I also discussed that some time ago. Long term, I still hope that at some point, we'll upstream `Astlib` to the compiler.

However, notice that I think there are two different things being mixed up here: the mentioned PR (#383), as well as what the `current-bench` team needs, as well as what it seems @panglesd has in mind ("To use ppxlib in a trunk switch"), is mere `trunk` support; i.e. being able to use `ppxlib` on a switch with `trunk` installed, on projects that don't use the new `trunk` features. What you seem to need, @shym, is `trunk` feature support. At least, that's what it seems to me from [a look at your fork](https://github.com/shym/ppxlib/blob/5.1/ast/import.ml#L7) and the fact that you mentioned `ast/ast.ml`. Is that right?

**Comment by shym** [comment]
I’m not sure I understand the nuance: I just want to be able to compile some code, which contains a few `[@@deriving`, in both 5.0 and 5.1. If I interpret correctly the distinction you’re making, that would fit in the first case, as the source code is really using 5.0 syntax.
The current content of my fork is the result of an effort to get `ppxlib` compiling on 5.1, patching all the places the compiler complained about. If it’s possible to get that result without so many changes, that would suit me perfectly.

**Comment by avsm** [comment]
Just to second this feature request, I could also _really_ use a version of ppxlib that tracks (lagging by a few weeks or a month) the syntax extensions in the trunk version of the compiler.  It makes it so much easier to develop multicore/effects code where we're using the latest features before the compiler gets released (and to test).

Am happy to use a branch of ppxlib that can be opam pinned, as I vendor in the sources into my own monorepos (such as https://github.com/avsm/eeww).

**Comment by shym** [comment]
Thank you for the step-by-step guide! I think I must have followed randomly more or less such steps (more guided by compiler error messages than understanding, to be honest...), this will help if I have to redo it in a more principled fashion :smile:

I just rebased what the version I’m using with the trunk compiler in my [`trunk`](https://github.com/shym/ppxlib/tree/trunk) branch, that could serve as a draft for this. I explicitly did _not_ promote the results of `runtest`, because they look rather fishy (due to my `OCAMLRUNPARAM` maybe?).

About the difference between "only supporting the new compiler" and "supporting also the new compiler syntax features": I understand the general idea but not how to put it in use. For instance in the current example, if I want `ppxlib` to compile with the current trunk compiler, I need to support `Pmod_apply_unit`, and so... that’s how I ended up with that commit.

**Comment by avsm** [comment]
> If we only want to support compiling projects with trunk, and not compiling projects that use the new trunk's syntax features

That's exactly what I need -- no need for actually using the new features. Thanks!

**Comment by pitag-ha** [comment]
I've just created the branch we've been talking about: https://github.com/ocaml-ppx/ppxlib/tree/trunk-support. It's a manually maintained branch with non-continuous `trunk` support.

> I just rebased the version I’m using with the [trunk](https://github.com/shym/ppxlib/tree/trunk) compiler in my trunk branch, that could serve as a draft for this.

Thanks! That's been very helpful for me. I've indeed used your branch as a draft. Concretely, I've re-used your new `Astlib` modules and made you a co-author of the commit.

> I explicitly did not promote the results of runtest, because they look rather fishy (due to my OCAMLRUNPARAM maybe?).

You're right. There seems to have been a modification in the compiler-libs `Toplevel` library, which messes with our expect tests. I haven't looked into that, though. I'll look into it as part of the 5.1 release readiness phase.

> About the difference between "only supporting the new compiler" and "supporting also the new compiler syntax features": I understand the general idea but not how to put it in use.

I've tried to make the difference clear in the README of the branch. Could you let me know if that's clear? If not, I'll modify it.

**Comment by shym** [comment]
Thank you very much, both for the branch and the explanations; I found them clear, congratulations!
I completely agree with the strategy of addressing PPXs breakages and internal details only for released compilers.
