### ISSUE TITLE
Ignore more machine generated attributes

### ISSUE THREAD

**Issue by diml** [ocaml-ppx/ppxlib#40]
We currently whilelist merlin attributes as they can safely be dropped. Reason needs something similar, cf https://github.com/janestreet/ppx_inline_test/issues/15.

To be more generic, we can simply whitelist all attributes with a name starting with `_`. We should also whitelist specific existing reason attributes to make things simpler.

**Comment by sgrove** [comment]
Would love to see this happen, we can't add in some of our own ppx's because of Reason's tagging of string literals right now.

**Comment by diml** [comment]
I made the PR to ignore all attributes starting with `_`: #46

**Comment by diml** [comment]
The changes is merged, if someone can test that it works as expected, we'll submit a release.
