### ISSUE TITLE
Possibly wrong link for merlin

### ISSUE THREAD

**Issue by cionx** [ocaml-ppx/ppxlib#412]
https://github.com/ocaml-ppx/ppxlib/blob/499a836c9ef184d75e113fad9021a7a696448796/doc/driver.mld#L40-L41

The URL https://merlin.com leads to the homepage of a South American technology company named “merlin”. Is this really the intended URL? (I’d have expected something like https://ocaml.github.io/merlin/ instead.)

**Comment by panglesd** [comment]
Thanks for the report! Indeed, I guess the link was used as a placeholder when writing the doc, which was obviously a bad idea.

Would you like to open a PR fixing this? (but it'll appear on ocaml.org only at the next release).
