### ISSUE TITLE
Reduce the number of AST traversals

### ISSUE THREAD

**Issue by pitag-ha** [ocaml-ppx/ppxlib#438]
When the driver contains a deriver, it needs to take care of silencing w32 and w60 warnings: we consider it ok that items are derived without being used. Currently that's done via two extra AST passes. Those passes should be merged into the general context-free pass. See [ToDo inside code base](https://github.com/ocaml-ppx/ppxlib/blob/main/src/driver.ml#L681-L682).

I probably won't get to this myself right away. If anyone wants to work on this in the meanwhile, that sounds great. I think it's an interesting task.

**Comment by NathanReb** [comment]
I think this has been fixed and is now dealt with in context free deriving rules!

Please feel free to re-open if I missed something!
