### ISSUE TITLE
Compiler error with OCaml 5.2.0 and an identity ppx

### ISSUE THREAD

**Issue by Octachron** [ocaml-ppx/ppxlib#477]
Using the ppxlib preview for OCaml 5.2.0 leads to a compiler error appearing even for an identity ppx in the following configuration:

* `value.ml`:
 >```ocaml
 >   type t
 >```
* `symbol.ml`
>```ocaml
>    type t = private Value.t
>```
* `main.ml`
>```ocaml
> let f x = (x:Symbol.t :> Value.t)
>```
 (See https://github.com/Octachron/bug-reproduction-archives/tree/main/ppxlib_and_include for a full reproduction case)

The error disappear either when the identity ppx is not included, or when switching to a handwritten ppx.

**Comment by Octachron** [comment]
This seems indeed increasingly likely to be a ppxlib issue. Typically, my reproduction case at https://github.com/Octachron/bug-reproduction-archives/tree/main/ppxlib_and_include fails with the reported error whenever a ppxlib-based ppx is used (even for an identity ppx).

**Comment by hhugo** [comment]
ppxlib seems to rewrite
```ocaml
let f x = (x:Symbol.t :> Value.t)
```
into
```ocaml
let f x : Symbol.t:> Value.t= (x : Symbol.t  :> Value.t)
```

Here is the command I ran with yout repror epo
```
$ ocamlc -dsource _build/default/src/form.pp.ml 
[@@@ocaml.ppx.context
  {
    tool_name = "ppx_driver";
    include_dirs = [];
    hidden_include_dirs = [];
    load_path = ([], []);
    open_modules = [];
    for_package = None;
    debug = false;
    use_threads = false;
    use_vmthreads = false;
    recursive_types = false;
    principal = false;
    transparent_modules = false;
    unboxed_types = false;
    unsafe_string = false;
    cookies = [("library-name", "x")]
  }]
let f x : Symbol.t:> Value.t= (x : Symbol.t  :> Value.t)
File "src/form.ml", line 1, characters 14-22:
1 | let f x = (x: Symbol.t :> Value.t)
                  ^^^^^^^^
Error: Unbound module Symbol
```

**Comment by NathanReb** [comment]
I'm closing this as it's been fixed on [`trunk-support`](https://github.com/ocaml-ppx/ppxlib/tree/trunk-support)
