### ISSUE TITLE
Allow generation of type definitions using expression nodes

### ISSUE THREAD

**Issue by jaisw7** [ocaml-ppx/ppxlib#484]
Suppose, I want to expand 
```
type t = A [@len 2] 
[@@deriving abc]
```
to 
```
type t = A0 | A1
```

This is straightforward using ppxlib since `2` is a known constant. However, I was wondering if it's possible to generate type definitions based on expressions:

```
let x = Int.of_string "2" (* some arbitrary expression *)
type t = A [@len x] 
[@@deriving abc]
```

I am able to generate `let` bindings. But `type declarations`, to the best of my knowledge, seem to be impossible since the OCaml AST doesn't allow constructing a `core_type` using expressions.

**Comment by NathanReb** [comment]
I'm closing this, please feel free to re-open if you deem it necessary.
