### ISSUE TITLE
BUG: generating invalid ocaml syntax.

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ppxlib#485]
`ocamlformat.0.26.1` chokes on:
```
let _ =
  if x && try () with _ -> () then ()
```
when `.ocamlformat` contains
```
ocp-indent-compat
```

**Comment by panglesd** [comment]
Hello!

Maybe you meant to open this issue on https://github.com/ocaml-ppx/ocamlformat ? Otherwise, I'm not sure what you mean!

**Comment by nojb** [comment]
Oops, you are right. Sorry for the noise!
