### ISSUE TITLE
ppxlib v0.8.0 and v0.7.0- pretty print ASTs as code differently on ocaml >= 4.05

### ISSUE THREAD

**Issue by NathanReb** [ocaml-ppx/ppxlib#84]
I recently ran into this. It's not a major issue and although I know I shouldn't rely too much on the pretty printed ASTs, I do for testing which makes this a bit annoying.

For example, in `ppx_yojson` tests I diff the pretty printed post rewriting AST for the following piece of code:
```ocaml
let null : json = [%yojson None]
```
which, until now, was:
```ocaml
let null : json = `Null
```
for ocaml `4.04` to `4.07`.

With `ppxlib.0.8.0`, it is printed as:
```ocaml
let null = (`Null : json)
```
for ocaml 4.04 and 4.05 but still printed as above for ocaml 4.06 or higher.

Do you have any idea what lead to that change and if there's a way to fix it? Once again it's nothing major but if it's easy/quick enough I'll gladly take care of it!

I'm also curious how to use the `-styler` option of the standalone driver as it could offer me a way to work around that.

**Comment by xclerc** [comment]
We used to embed a slightly-modified parser,
but it was removed (see https://github.com/ocaml-ppx/ppxlib/pull/79).

**Comment by NathanReb** [comment]
Thanks for the pointer!

I found a decent workaround and I'm not sure it's worth fixing this in `ppxlib` right now so I'm closing the issue.
