### ISSUE TITLE
Export `Ast_pattern.drop` in module interface

### ISSUE THREAD

**Issue by kwshi** [ocaml-ppx/ppxlib#89]
`ast_pattern.ml` defines a `drop` pattern, which is used to match against _any_ pattern and then discard it without capturing.  Consider the following example: say I want to capture and do something to a `let .. = ..` declaration.  I would make a `pstr_value` pattern as follows:

```ocaml
val pstr_value : (rec_flag, 'a, 'b) t -> (value_binding list, 'b, 'c) t -> (structure_item, 'a, 'c) t
pstr_value __ __
```

Where the first `__` captures the recursive/non-recursive flag, and the second `__` captures the actual `.. = ..` pairs.  I would define a continuation to handle the captured values as such:

```ocaml
fun rec_flag bindings ->
  bindings
  |> List.map ..
```

But I'm not interested in the `rec_flag` at all!  I would much rather write

```ocaml
fun bindings ->
  bindings
  |> List.map ..
```

rather than have to prepend a `_` parameter, or have to change my handling function's signature every time the pattern is changed--for instance, if I have a function that transforms `value_binding`s in different contexts, and in some contexts, the pattern capturing the `value_binding` comes with an extra parameter, then instead of using the same handler function for both cases, I have to pass one of them through an extra `map` first if I want to reuse the same handler.  It would be much more convenient if I could write something like

```ocaml
pstr_value drop __
```

or, if one wants to get creative with symbols,

```ocaml
pstr_value ___ __
```

so that the value matched by the `___`/`drop` is effectively an "any" match without actually _capturing_ the value.  It would be somewhat similar to the `ptyp_any` pattern, which captures any type expression, but instead something like `pany_any`.

**Comment by pitag-ha** [comment]
Hey @kwshi , thanks for the issue (even though I'm saying this 2,5 years late)! The detailed description has served very well as an example recently for the same issue #310. #313 has should resolve both those issues, so I'm closing this now.
