### ISSUE TITLE
Request for docs: The `?attributes` parameter in Deriving.Generator.make 

### ISSUE THREAD

**Issue by rgrinberg** [ocaml-ppx/ppxlib#90]
The function make takes this `?attributes` argument but as far as I can tell doesn't do anything except store it. I've dug into the source and I see some commented source that would remove this attribute, but this is no longer done. Can the purpose of this argument be documented perhaps?

**Comment by diml** [comment]
It's unused right now. It wasn't deleted for backward compatibility reason. We can delete in in the `ppx` library

**Comment by rgrinberg** [comment]
I think it would make sense to deprecate this parameter in ppxlib then.

**Comment by diml** [comment]
Is it possible to deprecate a parameter?

**Comment by rgrinberg** [comment]
I'm not sure, but if it's not, then it would be quite useful to have that.

**Comment by diml** [comment]
Indeed. I don't think it's possible, but if it is, happy for it be deprecated!
